// Generated by scripts/check-samples.mjs. Do not edit by hand.
/** Prompts that have a Chép mẫu sample essay. */
export const SAMPLE_IDS: ReadonlySet<string> = new Set(["cheaper-international-travel","childcare-training","city-traffic"]);
