/**
 * Task 2 prompt library with per-question metadata.
 *
 * Each prompt is a list of questions; a question's `shape` decides which lens chips show, whether the
 * rope + stance appear (verdict only) and whether solutions must link to a cause/problem.
 * `sides` are the rope ends for verdict questions: [left = against / second view, right = for / first view].
 *
 * Sources: most prompts are from youpass.vn's Task 2 bank (exam reports and collections), metadata written
 * by hand for this app; a few are design samples covering question types the bank lacks.
 * Move this into D1 once prompts are edited from an admin page.
 */
import type { PromptSpec, Question, Shape } from '@/features/chainlab/types';

export type Task = 'task1' | 'task2';

export const CATEGORIES_TASK2 = ['Agree or Disagree', 'Discussion', 'Advantages and Disadvantages', 'Causes, Problems and Solutions', 'Two-Part Question', 'Positive or Negative Development'] as const;
export const CATEGORIES_TASK1 = ['Line Graph', 'Bar Chart', 'Pie Chart', 'Table', 'Process', 'Map', 'Mixed Charts'] as const;
export const TOPICS_TASK2 = ['Education', 'Environment', 'Work and Careers', 'Government & Criminal Justice', 'Science and Technology', 'Health', 'Entertainment', 'Society and Culture', 'Economics', 'Other Topics', 'Travel and Transportation'] as const;

export type Category = (typeof CATEGORIES_TASK2)[number];
export type Topic = (typeof TOPICS_TASK2)[number];

export interface Prompt extends PromptSpec {
  task: Task;
  category: Category;
  topic: Topic;
  /** Where the prompt came from, e.g. "YouPass · Actual Test". */
  source: string;
  reqs: string[];
  driver: string;
  stakeholders: string[];
}

// ---- Question helpers -------------------------------------------------------
const q = (n: number, shape: Shape, text: string, sides?: [string, string]): Question => ({ n, shape, q: text, ...(sides ? { sides } : {}) });
/** Agree / disagree. */
const ag = (text: string) => [q(1, 'verdict', text, ['Phản đối', 'Đồng ý'])];
/** Do the advantages outweigh the disadvantages? */
const ow = (text: string) => [q(1, 'verdict', text, ['Nhược điểm', 'Ưu điểm'])];
/** Positive or negative development? */
const pn = (text: string) => [q(1, 'verdict', text, ['Tiêu cực', 'Tích cực'])];
/** Discuss both views and give your opinion: [left = second view, right = first view]. */
const dv = (text: string, left: string, right: string) => [q(1, 'verdict', text, [left, right])];

const DISCUSS_REQS = ['Bàn cả hai quan điểm, mỗi bên có lý do riêng.', 'Nêu rõ bạn nghiêng về bên nào, và trong điều kiện nào.'];
const SOLUTION_REQ = 'Câu ②: mỗi giải pháp phải xử lý một nguyên nhân ở câu ①.';

const YP = 'YouPass';
const SAMPLE = 'hocnoihocviet · đề mẫu';
/** Prompts worked through in The Art of Nuance (Phase 2 examples); their Chép mẫu sample is the book's own essay. */
const BOOK = 'The Art of Nuance · ví dụ trong sách';

type Entry = Omit<Prompt, 'task'>;

const ENTRIES: Entry[] = [
  // ---------------- Agree or Disagree ----------------
  { id: 'childcare-training', source: SAMPLE, category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Caring for children is an important responsibility. Some people believe that all parents should be required to take childcare training courses. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Đưa ra lập trường rõ ràng về yêu cầu được đề xuất.', 'Đánh giá tác động của yêu cầu, không bàn chung về việc học chăm sóc trẻ.', 'Xét phạm vi áp dụng cho tất cả phụ huynh.'],
    driver: 'Requiring every parent to complete childcare training', stakeholders: ['Phụ huynh', 'Trẻ em', 'Nơi làm việc', 'Đơn vị đào tạo', 'Chính phủ'] },
  { id: 'prison-vs-education', source: YP + ' · bài chấm mẫu', category: 'Agree or Disagree', topic: 'Education',
    text: 'Prison is the common way in most countries to solve the problem of crime. However, a more effective solution is to provide people with a better education. To what extent do you agree or disagree with this opinion?',
    questions: ag('To what extent do you agree or disagree with this opinion?'),
    reqs: ['Nói rõ giáo dục có hiệu quả hơn nhà tù trong việc giảm tội phạm hay không, và trong điều kiện nào.', 'So sánh hai cách, không chỉ bàn riêng về giáo dục.'],
    driver: 'Providing people with better education instead of relying on prison', stakeholders: ['Người phạm tội', 'Nạn nhân và cộng đồng', 'Nhà trường', 'Chính phủ'] },
  { id: 'compulsory-community-service', source: YP + ' · Actual Test', category: 'Agree or Disagree', topic: 'Education',
    text: 'Some people believe that unpaid community service should be a compulsory part of high school programmes (for example working for charity, improving the neighborhood, or teaching sports to young children). To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên bắt buộc hay không, và trong điều kiện nào.', 'Xét hai chữ "compulsory" và "unpaid": khác gì so với để học sinh tự nguyện?'],
    driver: 'Making unpaid community service compulsory in high school', stakeholders: ['Học sinh', 'Nhà trường', 'Tổ chức cộng đồng, từ thiện', 'Phụ huynh'] },
  { id: 'tall-apartment-blocks', source: YP + ' · IELTS Insights 07/2026', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'The best way to provide enough homes in large cities is to build tall apartment blocks. To what extent do you agree or disagree with this statement?',
    questions: ag('To what extent do you agree or disagree with this statement?'),
    reqs: ['Nói rõ chung cư cao tầng có phải cách tốt nhất hay không.', 'Chữ "the best way": cần so với các cách khác, không chỉ nói lợi ích của chung cư.'],
    driver: 'Building tall apartment blocks to house city residents', driver2: 'Building new homes in smaller towns near the city', claim: 'best', stakeholders: ['Cư dân thành phố', 'Chính quyền', 'Chủ đầu tư', 'Gia đình có trẻ nhỏ'] },
  { id: 'fast-food-regulation', source: YP + ' · Actual Test', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Governments should impose stricter regulations on fast food to promote public health. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên siết quy định hay không, và loại quy định nào.', 'Gắn với mục tiêu "public health": quy định có thật sự làm sức khoẻ tốt hơn không?'],
    driver: 'Stricter government regulation of fast food', stakeholders: ['Người tiêu dùng', 'Chuỗi đồ ăn nhanh', 'Hệ thống y tế', 'Chính phủ'] },
  { id: 'parenting-skills-at-school', source: YP + ' · Actual Test', category: 'Agree or Disagree', topic: 'Education',
    text: 'Some people say schools should teach parenting skills to young people. Do you agree or disagree?',
    questions: ag('Do you agree or disagree?'),
    reqs: ['Nói rõ trường học có nên dạy kỹ năng làm cha mẹ hay không, và cho lứa tuổi nào.', 'Xét cái giá: thời gian học, người dạy, môn khác bị cắt bớt.'],
    driver: 'Teaching parenting skills in schools', stakeholders: ['Học sinh', 'Giáo viên, nhà trường', 'Phụ huynh', 'Trẻ em tương lai'] },
  { id: 'young-offenders-as-adults', source: YP + ' · 19/8/2025', category: 'Agree or Disagree', topic: 'Government & Criminal Justice',
    text: 'Some people believe that young people who commit serious crimes should be punished in the same way as adults. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên xử phạt như người lớn hay không, và trong trường hợp nào.', 'Chữ "serious crimes": chỉ xét tội nghiêm trọng, không phải mọi vi phạm.'],
    driver: 'Punishing young people who commit serious crimes the same way as adults', stakeholders: ['Người phạm tội trẻ tuổi', 'Nạn nhân', 'Hệ thống tư pháp', 'Gia đình'] },
  { id: 'younger-leaders', source: YP + ' · 18/1/2025', category: 'Agree or Disagree', topic: 'Work and Careers',
    text: 'Directors and managers of organisations are often older people. Some people say that it is better for younger people to be leaders. To what extent do you agree?',
    questions: ag('To what extent do you agree?'),
    reqs: ['Nói rõ người trẻ có nên làm lãnh đạo hơn không, và trong loại tổ chức nào.', 'So sánh với người lớn tuổi, không chỉ kể ưu điểm của người trẻ.'],
    driver: 'Appointing younger people as leaders of organisations', stakeholders: ['Nhân viên', 'Lãnh đạo trẻ', 'Lãnh đạo lớn tuổi', 'Tổ chức, công ty'] },
  { id: 'traditional-vs-modern-games', source: YP + ' · 4/1/2025', category: 'Agree or Disagree', topic: 'Education',
    text: 'Some people think traditional games are better than modern games in helping children develop their abilities. To what extent do you agree?',
    questions: ag('To what extent do you agree?'),
    reqs: ['Nói rõ trò chơi truyền thống có giúp trẻ phát triển hơn không, và ở khả năng nào.', 'So sánh hai loại trò chơi trên cùng một khả năng (thể chất, xã hội, tư duy…).'],
    driver: 'Children playing traditional games instead of modern games', stakeholders: ['Trẻ em', 'Phụ huynh', 'Nhà trường', 'Nhà sản xuất trò chơi'] },
  { id: 'social-media-regulation', source: YP + ' · T03/2026', category: 'Agree or Disagree', topic: 'Government & Criminal Justice',
    text: 'Governments should regulate the use of social media platforms to protect citizens from harmful content. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ chính phủ có nên quản lý mạng xã hội hay không, và đến mức nào.', 'Gắn với mục tiêu bảo vệ người dân khỏi nội dung độc hại: cái giá là gì?'],
    driver: 'Government regulation of social media platforms', stakeholders: ['Người dùng', 'Nền tảng mạng xã hội', 'Chính phủ', 'Trẻ em'] },
  { id: 'road-safety-punishments', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Government & Criminal Justice',
    text: 'The only way to improve safety on our roads is to give much stricter punishments for driving offences. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ phạt nặng có phải cách duy nhất không.', 'Chữ "the only way": cần xét các cách khác, không chỉ nói phạt nặng có tác dụng.'],
    driver: 'Much stricter punishments for driving offences', driver2: 'Redesigning roads and adding speed cameras', claim: 'only', stakeholders: ['Người lái xe', 'Cảnh sát giao thông', 'Người đi bộ', 'Chính phủ'] },
  { id: 'school-arts-vs-professional', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Government money should be spent on encouraging children to take part in sports and arts in schools rather than supporting professional sports and artistic performances for the general public. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên ưu tiên trẻ em ở trường hơn thể thao, nghệ thuật chuyên nghiệp không.', 'Đây là so sánh hai cách chi tiền: xét cả hai bên, không chỉ bên trẻ em.'],
    driver: 'Spending government money on school sports and arts instead of professional performances', stakeholders: ['Học sinh', 'Vận động viên, nghệ sĩ chuyên nghiệp', 'Công chúng', 'Chính phủ'] },
  { id: 'children-watching-tv', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Education',
    text: 'Children can learn effectively by watching television. Therefore, they should be encouraged to watch television regularly at home and at school. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên khuyến khích trẻ xem tivi thường xuyên không.', 'Đề có hai bước: tivi giúp học hiệu quả, nên khuyến khích xem thường xuyên. Xét cả bước suy luận này.'],
    driver: 'Encouraging children to watch television regularly at home and at school', stakeholders: ['Trẻ em', 'Phụ huynh', 'Giáo viên', 'Đài truyền hình'] },
  { id: 'success-and-luck', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Work and Careers',
    text: 'Some people believe that success in life is mostly a matter of luck. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ thành công có chủ yếu do may mắn hay không.', 'Chữ "mostly": không cần phủ nhận may mắn, mà xét nó có chiếm phần lớn hay không.'],
    driver: 'Success depending mostly on luck', stakeholders: ['Cá nhân', 'Gia đình', 'Nhà trường', 'Xã hội'] },
  { id: 'paternity-leave', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Work and Careers',
    text: 'All fathers should be entitled to time off from work after a child is born. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ mọi người cha có nên được nghỉ hay không.', 'Chữ "all fathers": xét cả nơi làm việc nhỏ và người lao động tự do.'],
    driver: 'Entitling all fathers to time off work after a birth', stakeholders: ['Người cha', 'Người mẹ và em bé', 'Nơi làm việc', 'Chính phủ'] },
  { id: 'space-exploration-spending', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Many people claim that spending money on developing technology for space exploration is unjustifiable. They believe there are more beneficial ways to use this money. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ chi tiền cho công nghệ thám hiểm vũ trụ có hợp lý không.', 'Đề so sánh với "cách dùng tiền có ích hơn": cần xét cách đó là gì.'],
    driver: 'Spending money on space exploration technology', stakeholders: ['Nhà khoa học', 'Người đóng thuế', 'Chính phủ', 'Người nghèo cần hỗ trợ'] },
  { id: 'restore-old-buildings', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Restoration of old buildings in main cities involves enormous government expenditure. Some people think this money would be better spent on building new houses and roads. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ tiền nên dùng xây nhà, đường mới thay vì trùng tu hay không.', 'So sánh hai cách dùng tiền, không chỉ nói một bên.'],
    driver: 'Spending restoration money on new houses and roads instead', stakeholders: ['Cư dân thành phố', 'Chính quyền', 'Du khách', 'Thế hệ sau'] },
  { id: 'work-and-meaning', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Work and Careers',
    text: 'The most important element in a person’s life is their work. Without a satisfying career, life is meaningless. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ công việc có phải yếu tố quan trọng nhất không.', 'Đề có hai ý: công việc quan trọng nhất, và không có sự nghiệp thì cuộc sống vô nghĩa. Xét cả hai.'],
    driver: 'Treating work as the most important element of life', driver2: 'Putting family, health and relationships ahead of work', claim: 'best', stakeholders: ['Người lao động', 'Gia đình', 'Người không đi làm (nghỉ hưu, nội trợ)', 'Xã hội'] },
  { id: 'local-vs-global-environment', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Environment',
    text: 'The government should reduce the amount of money spent on local environmental problems and instead increase funding for urgent and more threatening issues such as global warming. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên chuyển tiền từ vấn đề địa phương sang vấn đề toàn cầu không.', 'So sánh hai cách dùng tiền, xét cả người dân địa phương.'],
    driver: 'Moving environmental funding from local problems to global warming', stakeholders: ['Người dân địa phương', 'Chính phủ', 'Thế hệ sau', 'Doanh nghiệp'] },
  { id: 'work-only-for-money', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'The only reason why people work hard is to earn money and there is no other reason for doing so. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ tiền có phải lý do duy nhất không.', 'Chữ "the only reason": chỉ cần một lý do khác có thật là đủ để phản bác.'],
    driver: 'Working hard only to earn money', driver2: 'Working hard for reasons other than money, such as purpose, enjoyment or recognition', claim: 'only', stakeholders: ['Người lao động', 'Gia đình', 'Công ty', 'Xã hội'] },
  { id: 'one-job-vs-switching', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Some people think that people who choose a job early and keep doing it are more likely to get a satisfying career life than those who frequently change jobs. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ nhóm nào dễ có sự nghiệp hài lòng hơn.', 'Định nghĩa "satisfying career" trước khi so sánh hai nhóm.'],
    driver: 'Choosing a job early and staying in it', stakeholders: ['Người lao động', 'Công ty', 'Gia đình', 'Thị trường lao động'] },
  { id: 'school-until-18', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Education',
    text: 'Some people believe that students should not be allowed to leave school before the age of 18. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên cấm rời trường trước 18 tuổi không.', 'Xét những học sinh muốn đi làm hoặc học nghề sớm.'],
    driver: 'Not allowing students to leave school before 18', stakeholders: ['Học sinh', 'Phụ huynh', 'Nhà trường', 'Doanh nghiệp'] },
  { id: 'trees-vs-housing', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Environment',
    text: 'Some people say it is more important to plant trees in the open spaces in towns and cities than to build more housing. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ trồng cây có quan trọng hơn xây nhà không.', 'So sánh hai cách dùng đất trống, xét cả người đang thiếu nhà ở.'],
    driver: 'Planting trees in open urban spaces instead of building housing', stakeholders: ['Cư dân thành phố', 'Người thiếu nhà ở', 'Chính quyền', 'Môi trường'] },
  { id: 'ban-competitive-sports', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Some people think that competitive sports have a negative effect on children because they cause a fear of losing. Therefore, competitive sports should be banned for young people. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ có nên cấm thể thao thi đấu với người trẻ không.', 'Đề có hai bước: thể thao gây sợ thua, nên cấm. Xét cả bước suy luận này.'],
    driver: 'Banning competitive sports for young people', stakeholders: ['Trẻ em', 'Phụ huynh', 'Huấn luyện viên', 'Nhà trường'] },
  { id: 'school-purpose-citizens', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Some people think the main purpose of school is to turn children into good citizens and workers, rather than to benefit them as individuals. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ theo bạn mục đích chính của trường học là gì.', 'Đề đặt hai mục đích đối lập: xét chúng có thật sự loại trừ nhau không.'],
    driver: 'Schools focusing on producing good citizens and workers', driver2: 'Schools focusing on benefiting children as individuals', stakeholders: ['Học sinh', 'Nhà trường', 'Doanh nghiệp', 'Xã hội'] },
  { id: 'advertising-unnecessary', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'If a product is good or it meets people’s needs, people will buy it. Therefore, advertising is unnecessary and no more than entertainment. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ quảng cáo có thật sự không cần thiết không.', 'Đề có hai bước: hàng tốt tự bán được, nên quảng cáo vô ích. Xét cả bước suy luận này.'],
    driver: 'Treating advertising as unnecessary', stakeholders: ['Người tiêu dùng', 'Doanh nghiệp nhỏ', 'Doanh nghiệp lớn', 'Ngành quảng cáo'] },
  { id: 'business-social-responsibility', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'As well as making money, businesses also have social responsibilities. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ doanh nghiệp có trách nhiệm xã hội hay không, và trách nhiệm gì.', 'Chữ "as well as": trách nhiệm xã hội đi cùng lợi nhuận, không thay thế nó.'],
    driver: 'Businesses taking on social responsibilities', stakeholders: ['Doanh nghiệp', 'Nhân viên', 'Cộng đồng', 'Cổ đông'] },
  { id: 'technology-free-time', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Science and Technology',
    text: 'It was predicted that people living in the twenty-first century would have more free time than ever before because of improvements in technology. To what extent has this prediction come true?',
    questions: [q(1, 'verdict', 'To what extent has this prediction come true?', ['Chưa đúng', 'Đã đúng'])],
    reqs: ['Nói rõ dự đoán đã thành sự thật đến mức nào, và với ai.', 'Tách công nghệ tiết kiệm thời gian và công nghệ lấy thêm thời gian của người ta.'],
    driver: 'Technology giving people more free time', stakeholders: ['Người lao động', 'Gia đình', 'Công ty', 'Người lớn tuổi'] },
  { id: 'university-places', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Education',
    text: 'It is neither possible nor useful for a country to provide university places for a high proportion of young people. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Đề có hai ý: không khả thi và không có ích. Xét riêng từng ý.', 'Nói rõ bạn đồng ý đến mức nào, và với loại đất nước nào.'],
    driver: 'Providing university places for a high proportion of young people', stakeholders: ['Người trẻ', 'Trường đại học', 'Chính phủ', 'Thị trường lao động'] },
  { id: 'workforce-vs-academic', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Education',
    text: 'Schools should focus more on teaching students how to be successful in the workforce and less on helping them to achieve academic success. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ trường học có nên ưu tiên kỹ năng đi làm hơn thành tích học tập không.', 'Chữ "more… less": đây là chuyện tỉ lệ, không phải bỏ hẳn một bên.'],
    driver: 'Schools focusing on workforce skills over academic success', stakeholders: ['Học sinh', 'Giáo viên', 'Nhà tuyển dụng', 'Trường đại học'] },
  { id: 'stop-economic-development', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Environment',
    text: 'Some people argue that economic development causes serious harm to the environment, so they believe we should stop developing further in order to protect it. Do you agree or disagree?',
    questions: ag('Do you agree or disagree?'),
    reqs: ['Nói rõ có nên ngừng phát triển kinh tế để bảo vệ môi trường không.', 'Đề có hai bước: phát triển gây hại, nên ngừng phát triển. Xét cả bước suy luận này.'],
    driver: 'Stopping further economic development to protect the environment', stakeholders: ['Người dân nước nghèo', 'Doanh nghiệp', 'Chính phủ', 'Môi trường'] },
  { id: 'team-vs-solo-activities', source: YP + ' · IELTS Insights 01/2026', category: 'Agree or Disagree', topic: 'Education',
    text: 'Group or team activities can teach more important skills for life than those activities which are done alone. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ hoạt động nhóm có dạy được kỹ năng sống quan trọng hơn không.', 'So sánh hai loại hoạt động trên cùng loại kỹ năng.'],
    driver: 'Learning life skills through group or team activities', stakeholders: ['Học sinh', 'Giáo viên', 'Nhà tuyển dụng', 'Gia đình'] },
  { id: 'customs-and-traditions', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Society and Culture',
    text: 'Many customs and traditional ways of behavior are no longer relevant to modern life and not worth keeping. Do you agree or disagree?',
    questions: ag('Do you agree or disagree?'),
    reqs: ['Nói rõ phong tục truyền thống có còn đáng giữ không.', 'Chữ "many": không cần bàn mọi phong tục, mà xét những loại nào.'],
    driver: 'Abandoning customs and traditions', stakeholders: ['Người trẻ', 'Người lớn tuổi', 'Cộng đồng', 'Ngành du lịch'] },
  { id: 'life-without-work', source: YP + ' Collect', category: 'Agree or Disagree', topic: 'Work and Careers',
    text: 'If people could choose between a life without working or a life spending too much time working, people would choose a life without work. To what extent do you agree or disagree?',
    questions: ag('To what extent do you agree or disagree?'),
    reqs: ['Nói rõ người ta có chọn cuộc sống không làm việc hay không.', 'Đề so sánh hai cực: không làm gì và làm quá nhiều.'],
    driver: 'Choosing a life without work', stakeholders: ['Cá nhân', 'Gia đình', 'Xã hội', 'Nền kinh tế'] },

  // ---------------- Discussion ----------------
  { id: 'study-any-subject', source: SAMPLE, category: 'Discussion', topic: 'Education',
    text: 'Some people think university students should study whatever they like. Others believe they should only study subjects that will be useful in the future, such as science and technology. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Môn có ích', 'Môn yêu thích'), reqs: DISCUSS_REQS,
    driver: 'Letting students choose any subject they like', driver2: 'Requiring students to study only subjects that will be useful in the future', stakeholders: ['Sinh viên', 'Trường đại học', 'Nhà tuyển dụng', 'Xã hội'] },
  { id: 'international-news-subject', source: 'hocnoihocviet', category: 'Discussion', topic: 'Education',
    text: 'Some people think secondary school students should study international news as one of their subjects, while others believe that this is a waste of valuable school time? Discuss both these views and give your own opinion.',
    questions: dv('Discuss both these views and give your own opinion.', 'Lãng phí thời gian', 'Nên học'), reqs: DISCUSS_REQS,
    driver: 'Teaching international news as a school subject', stakeholders: ['Học sinh', 'Giáo viên', 'Phụ huynh', 'Nhà trường'] },
  { id: 'university-admission', source: 'hocnoihocviet', category: 'Discussion', topic: 'Education',
    text: 'Many people believe that universities should only offer places to students with the highest marks. Others say they should accept people of all ages, even if they did not do well at school. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Nhận mọi lứa tuổi', 'Chỉ nhận điểm cao'), reqs: DISCUSS_REQS,
    driver: 'Universities admitting only top-scoring students', driver2: 'Universities accepting people of all ages, whatever their marks at school', stakeholders: ['Học sinh giỏi', 'Người học muộn', 'Trường đại học', 'Xã hội'] },
  { id: 'technology-isolation', source: YP + ' Collect', category: 'Discussion', topic: 'Science and Technology',
    text: 'Some people think that technology makes people more isolated, while others believe it helps people communicate better. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Giao tiếp tốt hơn', 'Cô lập hơn'), reqs: DISCUSS_REQS,
    driver: 'People relying on technology to communicate', stakeholders: ['Người trẻ', 'Người lớn tuổi', 'Gia đình', 'Công ty công nghệ'] },
  { id: 'dependent-vs-independent', source: YP + ' · IELTS Insights 08/2026', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think that in the modern world we are becoming more dependent on each other, while others believe people have become more independent. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Độc lập hơn', 'Phụ thuộc hơn'), reqs: DISCUSS_REQS,
    driver: 'Modern life making people more dependent on each other', stakeholders: ['Cá nhân', 'Gia đình', 'Cộng đồng', 'Nơi làm việc'] },
  { id: 'scheduled-activities-vs-free-play', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people believe that children’s time outside of school should be filled with scheduled activities such as art and music classes and sports. Others feel that children need free time to play and relax. Discuss both these views and give your own opinion.',
    questions: dv('Discuss both these views and give your own opinion.', 'Thời gian tự do', 'Lịch hoạt động'), reqs: DISCUSS_REQS,
    driver: 'Filling children’s free time with scheduled activities', driver2: 'Leaving children’s free time unstructured for play and rest', stakeholders: ['Trẻ em', 'Phụ huynh', 'Trung tâm năng khiếu', 'Nhà trường'] },
  { id: 'theatres-and-cinemas', source: YP + ' · IELTS Insights 07/2026', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people say that in the digital age, theatres and cinemas are no longer important, as people can watch all the entertainment they want online. Others argue that theatres and cinemas are still important both economically and culturally. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Vẫn quan trọng', 'Không còn quan trọng'),
    reqs: [...DISCUSS_REQS, 'Quan điểm thứ hai nêu hai lý do: kinh tế và văn hoá. Xét cả hai.'],
    driver: 'Watching entertainment online instead of at theatres and cinemas', driver2: 'Keeping theatres and cinemas as places to watch entertainment', stakeholders: ['Khán giả', 'Rạp hát, rạp chiếu phim', 'Nghệ sĩ', 'Thành phố'] },
  { id: 'family-history', source: YP + ' · 07/03/2026', category: 'Discussion', topic: 'Society and Culture',
    text: 'In many parts of the world, people do research on their family history. Some people believe that finding out about previous generations is a useful thing to do. However, others believe that it is better to focus on present and future generations. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Tập trung hiện tại', 'Tìm hiểu tổ tiên'), reqs: DISCUSS_REQS,
    driver: 'Researching family history', driver2: 'Focusing on present and future generations instead of the past', stakeholders: ['Cá nhân', 'Gia đình', 'Thế hệ trẻ', 'Xã hội'] },
  { id: 'signals-to-aliens', source: YP + ' · 05/04/2026', category: 'Discussion', topic: 'Science and Technology',
    text: 'Some scientists believe that there are intelligent life forms on other planets and we should send messages into space to connect with them. Other scientists think that connecting with them is too dangerous. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Quá nguy hiểm', 'Nên gửi tín hiệu'), reqs: DISCUSS_REQS,
    driver: 'Sending messages into space to contact other life forms', stakeholders: ['Nhà khoa học', 'Chính phủ', 'Nhân loại', 'Người đóng thuế'] },
  { id: 'countryside-vs-city-health', source: YP + ' · 27/9/2025', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people believe that it is easier to have a healthy lifestyle in the countryside. Others believe that there are health benefits of living in cities. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Lợi ích ở thành phố', 'Dễ hơn ở nông thôn'), reqs: DISCUSS_REQS,
    driver: 'Living in the countryside for a healthier lifestyle', driver2: 'Living in cities for the health benefits they offer', stakeholders: ['Cư dân nông thôn', 'Cư dân thành phố', 'Hệ thống y tế', 'Người lớn tuổi'] },
  { id: 'minerals-in-space', source: YP + ' · IELTS Insights 06/2026', category: 'Discussion', topic: 'Science and Technology',
    text: 'Some people think that it is worth researching different minerals in space. Others, however, disagree. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Không đáng', 'Đáng nghiên cứu'), reqs: DISCUSS_REQS,
    driver: 'Researching minerals in space', stakeholders: ['Nhà khoa học', 'Chính phủ', 'Người đóng thuế', 'Ngành công nghiệp'] },
  { id: 'single-global-language', source: YP + ' · T04/2026', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some argue that a single global language should be taught in all schools. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Phản đối', 'Đồng ý'),
    reqs: ['Đề chỉ nêu một quan điểm: bạn tự dựng quan điểm ngược lại rồi bàn cả hai.', 'Nêu rõ bạn nghiêng về bên nào, và trong điều kiện nào.'],
    driver: 'Teaching one global language in all schools', stakeholders: ['Học sinh', 'Giáo viên ngôn ngữ', 'Cộng đồng ngôn ngữ thiểu số', 'Chính phủ'] },
  { id: 'criticising-teachers', source: YP + ' · 15/01/2025', category: 'Discussion', topic: 'Education',
    text: 'Some people think that in order to continuously improve the quality of education, high school students should be encouraged to criticise their teachers. Others think that would result in a loss of principle in class. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Mất kỷ cương', 'Nên khuyến khích'), reqs: DISCUSS_REQS,
    driver: 'Encouraging high school students to criticise their teachers', stakeholders: ['Học sinh', 'Giáo viên', 'Nhà trường', 'Phụ huynh'] },
  { id: 'remote-work-who-benefits', source: YP + ' Collect', category: 'Discussion', topic: 'Work and Careers',
    text: 'Some people think that remote working benefits employees the most, while others believe it only advantages employers. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Lợi cho chủ', 'Lợi cho nhân viên'), reqs: DISCUSS_REQS,
    driver: 'Remote working', stakeholders: ['Nhân viên', 'Chủ doanh nghiệp', 'Gia đình', 'Thành phố'] },
  { id: 'free-education-all-levels', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people believe that the government should provide free education at all levels, while others argue that students should pay for their university education. Discuss both views and give your own opinion',
    questions: dv('Discuss both views and give your own opinion', 'Sinh viên tự trả', 'Miễn phí mọi cấp'), reqs: DISCUSS_REQS,
    driver: 'Government-funded free education at all levels', driver2: 'Students paying for their own university education', stakeholders: ['Sinh viên', 'Gia đình', 'Chính phủ, người đóng thuế', 'Trường đại học'] },
  { id: 'group-vs-solo-study', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people think that it is more effective for students to study in a group, while others believe that it is better for them to study alone. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Học một mình', 'Học nhóm'), reqs: DISCUSS_REQS,
    driver: 'Students studying in groups', driver2: 'Students studying alone', stakeholders: ['Học sinh', 'Giáo viên', 'Phụ huynh', 'Nhà trường'] },
  { id: 'social-life-at-work', source: YP + ' Collect', category: 'Discussion', topic: 'Work and Careers',
    text: 'Some people think a job not only provides income but also social life. Others think it is better to develop a social life with people you do not work with. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Ngoài nơi làm', 'Ở nơi làm việc'), reqs: DISCUSS_REQS,
    driver: 'Building a social life through work', driver2: 'Building a social life with people outside work', stakeholders: ['Người lao động', 'Đồng nghiệp', 'Gia đình, bạn bè', 'Công ty'] },
  { id: 'parental-supervision', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think parents should supervise their children’s activities closely, while others believe children should have more freedom. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Cho tự do', 'Giám sát chặt'), reqs: DISCUSS_REQS,
    driver: 'Parents closely supervising children’s activities', driver2: 'Giving children more freedom in their activities', stakeholders: ['Trẻ em', 'Phụ huynh', 'Nhà trường', 'Xã hội'] },
  { id: 'sports-funding-athletes', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think that governments should spend more money on sports facilities for top athletes. Others argue that this money should be spent on sports facilities for ordinary people. Discuss both sides and give your opinion.',
    questions: dv('Discuss both sides and give your opinion.', 'Cho người dân', 'Cho vận động viên'), reqs: DISCUSS_REQS,
    driver: 'Spending more on sports facilities for top athletes', driver2: 'Spending the money on sports facilities for ordinary people', stakeholders: ['Vận động viên', 'Người dân', 'Chính phủ', 'Ngành thể thao'] },
  { id: 'zoos', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think that zoos are cruel and should be closed down. Others, however, believe that zoos can be useful in protecting wild animals. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Có ích', 'Nên đóng cửa'), reqs: DISCUSS_REQS,
    driver: 'Closing down zoos', driver2: 'Keeping zoos open to protect wild animals', stakeholders: ['Động vật', 'Khách tham quan', 'Nhà bảo tồn', 'Nhân viên vườn thú'] },
  { id: 'free-libraries', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think the government should establish free libraries in each town. Others believe that it is a waste of money since people can access the Internet to obtain information. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Lãng phí', 'Nên xây'), reqs: DISCUSS_REQS,
    driver: 'Building free libraries in every town', stakeholders: ['Người dân', 'Học sinh, người thu nhập thấp', 'Chính quyền', 'Người đóng thuế'] },
  { id: 'junk-food-responsibility', source: YP + ' Collect', category: 'Discussion', topic: 'Health',
    text: 'Some people state that schools should have a social responsibility to encourage children not to eat junk food. Others believe that parents should take responsibility for their children\'s eating habits. Discuss both views and state your opinion',
    questions: dv('Discuss both views and state your opinion', 'Phụ huynh', 'Nhà trường'), reqs: DISCUSS_REQS,
    driver: 'Schools taking responsibility for children’s eating habits', driver2: 'Parents taking responsibility for children’s eating habits', stakeholders: ['Trẻ em', 'Phụ huynh', 'Nhà trường', 'Ngành thực phẩm'] },
  { id: 'subsidise-vs-tax-food', source: YP + ' Collect', category: 'Discussion', topic: 'Health',
    text: 'Some people think the government should subsidise fruits and vegetables to make healthy food more affordable. Others argue that the government should tax unhealthy food . Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Đánh thuế đồ ăn hại', 'Trợ giá rau quả'), reqs: DISCUSS_REQS,
    driver: 'Subsidising fruit and vegetables', driver2: 'Taxing unhealthy food', stakeholders: ['Người tiêu dùng', 'Nông dân', 'Ngành thực phẩm', 'Chính phủ'] },
  { id: 'art-talent', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people say that every human being can create art (e.g. painting), others think only the people born with the ability can create art. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Phải có năng khiếu', 'Ai cũng làm được'), reqs: DISCUSS_REQS,
    driver: 'Everyone being able to create art', stakeholders: ['Người học nghệ thuật', 'Nghệ sĩ', 'Nhà trường', 'Xã hội'] },
  { id: 'taxes-enough', source: YP + ' Collect', category: 'Discussion', topic: 'Government & Criminal Justice',
    text: 'Some people think paying taxes is a big enough contribution to their society, while others think people have more responsibilities as members of society than only paying taxes. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Còn trách nhiệm khác', 'Nộp thuế là đủ'), reqs: DISCUSS_REQS,
    driver: 'Treating paying taxes as enough contribution to society', stakeholders: ['Người dân', 'Chính phủ', 'Cộng đồng', 'Người yếu thế'] },
  { id: 'breadth-vs-depth', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people think that older school children should learn a wide range of subjects to acquire more knowledge, while other people believe they should learn a small number of subjects in detail. Discuss both views and give your opinion',
    questions: dv('Discuss both views and give your opinion', 'Ít môn, học sâu', 'Nhiều môn'), reqs: DISCUSS_REQS,
    driver: 'Older school children studying a wide range of subjects', driver2: 'Older school children studying a small number of subjects in detail', stakeholders: ['Học sinh', 'Giáo viên', 'Trường đại học', 'Nhà tuyển dụng'] },
  { id: 'extracurricular-vs-academic', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people believe schools should provide more extracurricular activities to support students’ overall development, while others think schools should concentrate mainly on academic learning. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Tập trung học thuật', 'Thêm ngoại khoá'), reqs: DISCUSS_REQS,
    driver: 'Schools providing more extracurricular activities', driver2: 'Schools concentrating mainly on academic learning', stakeholders: ['Học sinh', 'Giáo viên', 'Phụ huynh', 'Nhà trường'] },
  { id: 'individuals-vs-government-environment', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think that environmental problems are too big for individuals to solve, while others think that the government cannot solve these environmental problems unless individuals make some action. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Cần cá nhân', 'Quá lớn với cá nhân'), reqs: DISCUSS_REQS,
    driver: 'Leaving environmental problems to governments', driver2: 'Individuals taking action on environmental problems themselves', stakeholders: ['Cá nhân', 'Chính phủ', 'Doanh nghiệp', 'Môi trường'] },
  { id: 'climate-change-business', source: YP + ' Collect', category: 'Discussion', topic: 'Environment',
    text: 'Some people think that climate change could have a negative effect on business, while others think that it could create more business opportunities. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Tạo cơ hội', 'Có hại cho kinh doanh'), reqs: DISCUSS_REQS,
    driver: 'Climate change affecting business', stakeholders: ['Doanh nghiệp', 'Người lao động', 'Chính phủ', 'Người tiêu dùng'] },
  { id: 'prison-vs-alternatives', source: YP + ' Collect', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people think all lawbreakers should be sent to prison, while others believe that there are better alternatives (eg. community work). Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Có cách tốt hơn', 'Đi tù tất cả'), reqs: DISCUSS_REQS,
    driver: 'Sending all lawbreakers to prison', driver2: 'Using alternatives to prison, such as community work', stakeholders: ['Người phạm tội', 'Nạn nhân', 'Nhà tù, tư pháp', 'Cộng đồng'] },
  { id: 'newspapers-vs-other-media', source: YP + ' · IELTS Insights 01/2026', category: 'Discussion', topic: 'Science and Technology',
    text: 'Some people think that newspapers are the best way to get news. However, others believe that they can get news better through another media platform. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Nền tảng khác', 'Báo giấy'), reqs: DISCUSS_REQS,
    driver: 'Getting news from newspapers', driver2: 'Getting news from other media platforms', stakeholders: ['Người đọc', 'Toà soạn báo', 'Mạng xã hội', 'Người lớn tuổi'] },
  { id: 'elderly-life-now', source: YP + ' · IELTS Insights 01/2026', category: 'Discussion', topic: 'Society and Culture',
    text: 'Some people say that in the modern world, getting old is entirely bad. Others, however, say that life for the elderly nowadays is much better than it was in the past. Discuss both views and give your own opinion.',
    questions: dv('Discuss both views and give your own opinion.', 'Tốt hơn trước', 'Hoàn toàn xấu'), reqs: DISCUSS_REQS,
    driver: 'Growing old in the modern world', stakeholders: ['Người già', 'Con cháu', 'Hệ thống y tế', 'Xã hội'] },
  { id: 'purpose-of-education', source: YP + ' Collect', category: 'Discussion', topic: 'Education',
    text: 'Some people say that the purpose of education is to prepare individuals to be useful to society. Others say its purpose is to prepare individuals to achieve personal ambitions. Discuss both views and give your opinion.',
    questions: dv('Discuss both views and give your opinion.', 'Tham vọng cá nhân', 'Có ích cho xã hội'), reqs: DISCUSS_REQS,
    driver: 'Education preparing people to be useful to society', driver2: 'Education preparing people to achieve their personal ambitions', stakeholders: ['Học sinh', 'Gia đình', 'Nhà trường', 'Xã hội'] },

  // ---------------- Advantages and Disadvantages ----------------
  { id: 'gap-year-sample', source: SAMPLE, category: 'Advantages and Disadvantages', topic: 'Education',
    text: 'Many young people now take a gap year before starting university. Do the advantages of this outweigh the disadvantages?',
    questions: ow('Do the advantages of this outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm, rồi nói bên nào nặng hơn.', 'Nói rõ điều kiện khiến ưu điểm (hoặc nhược điểm) thắng.'],
    driver: 'Taking a gap year before university', stakeholders: ['Học sinh', 'Gia đình', 'Trường đại học', 'Nhà tuyển dụng'] },
  { id: 'study-abroad-or-placement', source: YP + ' · IELTS Insights 07/2026', category: 'Advantages and Disadvantages', topic: 'Education',
    text: 'All university undergraduate courses should include a period of time spent studying abroad or doing a work placement. Do you think the advantages of this would outweigh the disadvantages?',
    questions: ow('Do you think the advantages of this would outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm của việc bắt buộc mọi khoá đại học có kỳ du học hoặc thực tập, rồi nói bên nào nặng hơn.', 'Xét chữ "all": yêu cầu áp dụng cho mọi ngành và mọi sinh viên.'],
    driver: 'Requiring every undergraduate course to include study abroad or a work placement', stakeholders: ['Sinh viên', 'Trường đại học', 'Doanh nghiệp nhận thực tập', 'Gia đình'] },
  { id: 'credit-cards', source: YP + ' · IELTS Insights 08/2026', category: 'Advantages and Disadvantages', topic: 'Economics',
    text: 'Nowadays it is easy to apply for and be given a credit card. However, some people experience problems when they are not able to pay their debt back. In your opinion, do the advantages of credit cards outweigh the disadvantages?',
    questions: ow('In your opinion, do the advantages of credit cards outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm của thẻ tín dụng, rồi nói bên nào nặng hơn.', 'Đề nhấn vào việc thẻ dễ được cấp và có người không trả được nợ: xét ai dễ gặp rủi ro nhất.'],
    driver: 'Credit cards being easy to obtain', stakeholders: ['Người dùng thẻ', 'Ngân hàng', 'Cửa hàng, doanh nghiệp', 'Gia đình người mắc nợ'] },
  { id: 'studying-abroad', source: YP + ' Collect', category: 'Advantages and Disadvantages', topic: 'Education',
    text: 'More and more students choose to move to other countries to study for higher education. Do the advantages outweigh the disadvantages?',
    questions: ow('Do the advantages outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm của việc ra nước ngoài học đại học, rồi nói bên nào nặng hơn.', 'Xét cả sinh viên lẫn đất nước của họ.'],
    driver: 'Students moving abroad for higher education', stakeholders: ['Sinh viên', 'Gia đình', 'Nước sở tại', 'Nước nhà'] },
  { id: 'ai-replacing-workers', source: YP + ' · T03/2026', category: 'Advantages and Disadvantages', topic: 'Work and Careers',
    text: 'Artificial intelligence will eventually replace most human workers. Do the advantages of this development outweigh the disadvantages?',
    questions: ow('Do the advantages of this development outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm khi AI thay phần lớn người lao động, rồi nói bên nào nặng hơn.', 'Đề nói "most human workers": xét ở quy mô cả xã hội.'],
    driver: 'Artificial intelligence replacing most human workers', stakeholders: ['Người lao động', 'Doanh nghiệp', 'Người tiêu dùng', 'Chính phủ'] },
  { id: 'businesses-to-rural-areas', source: YP, category: 'Advantages and Disadvantages', topic: 'Economics',
    text: 'As transport and accommodation problems are increasing in many large cities, some governments are encouraging businesses to move to rural areas. Do you think the advantages outweigh the disadvantages?',
    questions: ow('Do you think the advantages outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm của việc đưa doanh nghiệp về nông thôn, rồi nói bên nào nặng hơn.', 'Xét cả thành phố lớn lẫn vùng nông thôn.'],
    driver: 'Encouraging businesses to move to rural areas', stakeholders: ['Doanh nghiệp', 'Nhân viên', 'Cư dân nông thôn', 'Thành phố lớn'] },
  { id: 'government-pays-fees', source: YP + ' Collect', category: 'Advantages and Disadvantages', topic: 'Education',
    text: 'In some countries, students pay their college or university fees, while in some others, the government pays for them. Do you think the advantages of the government paying the money outweigh the disadvantages?',
    questions: ow('Do you think the advantages of the government paying the money outweigh the disadvantages?'),
    reqs: ['So sánh ưu và nhược điểm khi nhà nước trả học phí, rồi nói bên nào nặng hơn.', 'Xét cả người không học đại học nhưng vẫn đóng thuế.'],
    driver: 'The government paying university fees', stakeholders: ['Sinh viên', 'Người đóng thuế', 'Trường đại học', 'Chính phủ'] },
  { id: 'gap-year-study', source: YP + ' Collect', category: 'Advantages and Disadvantages', topic: 'Education',
    text: 'Some school leavers go travelling or work for a period of time instead of going directly to university. Do you think this has more advantages or disadvantages for their study?',
    questions: ow('Do you think this has more advantages or disadvantages for their study?'),
    reqs: ['So sánh ưu và nhược điểm, rồi nói bên nào nặng hơn.', 'Đề hỏi riêng ảnh hưởng tới việc học, không phải tới cuộc sống nói chung.'],
    driver: 'Travelling or working before going to university', stakeholders: ['Học sinh', 'Gia đình', 'Trường đại học', 'Nhà tuyển dụng'] },

  // ---------------- Positive or Negative Development ----------------
  { id: 'cheaper-international-travel', source: SAMPLE, category: 'Positive or Negative Development', topic: 'Travel and Transportation',
    text: 'It has become easier and more affordable for people to travel to other countries. Is this a positive or negative development?',
    questions: pn('Is this a positive or negative development?'),
    reqs: ['Chốt rõ tích cực hay tiêu cực, không dừng ở "vừa lợi vừa hại".', 'So hai bên: bên nào đúng với nhiều người hơn, bên nào có cách khác để khắc phục.'],
    driver: 'International travel becoming easier and cheaper', stakeholders: ['Người trước đây không đủ tiền đi', 'Doanh nghiệp, người dân nơi du lịch', 'Môi trường', 'Hãng hàng không'] },
  { id: 'working-from-home', source: SAMPLE, category: 'Positive or Negative Development', topic: 'Work and Careers',
    text: 'More and more people are choosing to work from home. Is this a positive or negative development?',
    questions: pn('Is this a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực, và trong điều kiện nào.', 'Đánh giá chính xu hướng làm việc tại nhà, không bàn chung về công nghệ.'],
    driver: 'More people working from home', stakeholders: ['Người lao động', 'Công ty', 'Gia đình', 'Thành phố'] },
  { id: 'long-working-hours', source: YP + ' · Actual Test', category: 'Positive or Negative Development', topic: 'Work and Careers',
    text: 'In some countries, people are spending long hours at the workplace. Is it a positive or negative development?',
    questions: pn('Is it a positive or negative development?'),
    reqs: ['Nói rõ đây là xu hướng tích cực hay tiêu cực, và với ai.', 'Đánh giá chính việc làm nhiều giờ, không bàn chung về công việc.'],
    driver: 'People spending long hours at the workplace', stakeholders: ['Người lao động', 'Gia đình', 'Công ty', 'Nền kinh tế'] },
  { id: 'online-university-courses', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Education',
    text: 'More and more universities are replacing face-to-face teaching with online courses. Do you think this is a positive or negative development?',
    questions: pn('Do you think this is a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực, và với ai.', 'Đánh giá việc thay thế lớp trực tiếp, không chỉ việc có thêm khoá online.'],
    driver: 'Universities replacing face-to-face teaching with online courses', stakeholders: ['Sinh viên', 'Giảng viên', 'Trường đại học', 'Nhà tuyển dụng'] },
  { id: 'youth-in-malls', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Society and Culture',
    text: 'In many countries, young people spend a large amount of their free time in shopping malls rather than taking part in other activities such as sports or music. Is this a positive or negative development?',
    questions: pn('Is this a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực, và trong điều kiện nào.', 'Đề so sánh với thể thao, âm nhạc: xét cả những gì người trẻ bỏ lỡ.'],
    driver: 'Young people spending free time in shopping malls', stakeholders: ['Người trẻ', 'Phụ huynh', 'Trung tâm thương mại', 'Câu lạc bộ thể thao, âm nhạc'] },
  { id: 'children-more-freedom', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Society and Culture',
    text: 'In many parts of the world, children are given more freedom than in the past. Is this a positive or negative development?',
    questions: pn('Is this a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực, và là tự do kiểu gì.', 'So sánh với quá khứ như đề nêu.'],
    driver: 'Children being given more freedom than in the past', stakeholders: ['Trẻ em', 'Phụ huynh', 'Nhà trường', 'Xã hội'] },
  { id: 'tours-to-remote-places', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Travel and Transportation',
    text: 'Organised tours to remote places and communities are becoming more and more popular. Is it a positive or negative development to local people and the environment?',
    questions: pn('Is it a positive or negative development to local people and the environment?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực.', 'Đề hỏi riêng về người dân địa phương và môi trường: xét cả hai.'],
    driver: 'Organised tours to remote places and communities', stakeholders: ['Người dân địa phương', 'Du khách', 'Công ty du lịch', 'Môi trường'] },
  { id: 'international-food-in-supermarkets', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Economics',
    text: 'Supermarkets in many countries now stock a wide range of foods from different parts of the world. Do you consider this a positive or negative development?',
    questions: pn('Do you consider this a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực, và với ai.', 'Xét cả người tiêu dùng lẫn nông dân trong nước.'],
    driver: 'Supermarkets stocking food from around the world', stakeholders: ['Người tiêu dùng', 'Nông dân trong nước', 'Siêu thị', 'Môi trường'] },
  { id: 'space-tourism', source: YP + ' Collect', category: 'Positive or Negative Development', topic: 'Science and Technology',
    text: 'Space travel has been possible for some time and some people claim that space tourism could be developed in the future. Do you think it is a positive or negative development?',
    questions: pn('Do you think it is a positive or negative development?'),
    reqs: ['Nói rõ phát triển du lịch vũ trụ là tích cực hay tiêu cực.', 'Xét cả những người không bao giờ đi được: môi trường, chi phí xã hội.'],
    driver: 'Developing space tourism', stakeholders: ['Du khách giàu có', 'Công ty vũ trụ', 'Môi trường', 'Xã hội'] },
  { id: 'admiring-celebrities', source: YP + ' · 1/12/2025', category: 'Positive or Negative Development', topic: 'Society and Culture',
    text: 'Nowadays, young people are admiring media and sports stars, even though they often do not set a good example. Do you think this is a positive or negative development?',
    questions: pn('Do you think this is a positive or negative development?'),
    reqs: ['Nói rõ đây là tích cực hay tiêu cực.', 'Đề nói người nổi tiếng thường không làm gương tốt: xét chuyện này.'],
    driver: 'Young people admiring media and sports stars', stakeholders: ['Người trẻ', 'Phụ huynh', 'Người nổi tiếng', 'Truyền thông'] },

  // ---------------- Causes, Problems and Solutions ----------------
  { id: 'city-traffic', source: SAMPLE, category: 'Causes, Problems and Solutions', topic: 'Travel and Transportation',
    text: 'Many cities around the world have serious traffic problems. What are the causes of this? What can be done to solve it?',
    questions: [q(1, 'cause', 'What are the causes of this?'), q(2, 'solution', 'What can be done to solve it?')],
    reqs: ['Câu ①: nêu 2–3 nguyên nhân đúng với phần lớn thành phố.', SOLUTION_REQ],
    driver: 'Serious traffic congestion in cities', stakeholders: ['Người đi làm', 'Chính quyền thành phố', 'Doanh nghiệp vận tải', 'Cư dân'] },
  { id: 'obesity-problems', source: SAMPLE, category: 'Causes, Problems and Solutions', topic: 'Health',
    text: 'Obesity is rising in many countries. What problems does this cause? What can be done to tackle it?',
    questions: [q(1, 'problem', 'What problems does this cause?'), q(2, 'solution', 'What can be done to tackle it?')],
    reqs: ['Câu ①: nêu vấn đề do béo phì gây ra, không giải thích vì sao béo phì tăng.', 'Câu ②: mỗi giải pháp phải xử lý một vấn đề ở câu ①.'],
    driver: 'Rising obesity rates', stakeholders: ['Người béo phì', 'Gia đình', 'Hệ thống y tế', 'Nơi làm việc', 'Chính phủ'] },
  { id: 'car-ban-problems', source: SAMPLE, category: 'Causes, Problems and Solutions', topic: 'Travel and Transportation',
    text: 'A government plans to ban private cars from the city centre. What problems might this cause?',
    questions: [q(1, 'planproblem', 'What problems might this cause?')],
    reqs: ['Nêu vấn đề do lệnh cấm gây ra, không bàn chung về ô tô.', 'Xét ai bị ảnh hưởng nhiều nhất khi kế hoạch được áp dụng.'],
    driver: 'Banning private cars from the city centre', stakeholders: ['Người đi làm', 'Cửa hàng trung tâm', 'Người già, người khuyết tật', 'Chính quyền'] },
  { id: 'car-ban-solutions', source: SAMPLE, category: 'Causes, Problems and Solutions', topic: 'Travel and Transportation',
    text: 'A government plans to ban private cars from the city centre. What problems might this cause? How can these problems be solved?',
    questions: [q(1, 'planproblem', 'What problems might this cause?'), q(2, 'solution', 'How can these problems be solved?')],
    reqs: ['Câu ①: nêu vấn đề do lệnh cấm gây ra.', 'Câu ②: mỗi giải pháp phải xử lý một vấn đề ở câu ①.'],
    driver: 'Banning private cars from the city centre', stakeholders: ['Người đi làm', 'Cửa hàng trung tâm', 'Người già, người khuyết tật', 'Chính quyền'] },
  { id: 'declining-bicycle-use', source: YP + ' · 3/5/2025', category: 'Causes, Problems and Solutions', topic: 'Travel and Transportation',
    text: 'In certain countries, the number of people who use bicycles as the main means of transport is reducing even though it is beneficial both physically and environmentally. What can be the reasons for this change in preference? How can people be encouraged to use bicycles?',
    questions: [q(1, 'cause', 'What can be the reasons for this change in preference?'), q(2, 'solution', 'How can people be encouraged to use bicycles?')],
    reqs: ['Câu ①: giải thích vì sao người ta bỏ xe đạp dù nó có lợi cho sức khoẻ và môi trường.', SOLUTION_REQ],
    driver: 'Fewer people using bicycles as their main transport', stakeholders: ['Người đi làm', 'Chính quyền thành phố', 'Người đi xe máy, ô tô', 'Môi trường đô thị'] },
  { id: 'anti-social-behaviour', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Society and Culture',
    text: 'In many countries, there is a general increase in anti-social behaviour and a lack of respect for others. What are the causes of this and how can this situation be improved?',
    questions: [q(1, 'cause', 'What are the causes of this'), q(2, 'solution', 'how can this situation be improved?')],
    reqs: ['Câu ①: giải thích vì sao hành vi thiếu tôn trọng người khác tăng lên.', SOLUTION_REQ],
    driver: 'Rising anti-social behaviour and lack of respect', stakeholders: ['Người trẻ', 'Gia đình', 'Nhà trường', 'Cộng đồng, chính quyền'] },
  { id: 'global-environment-solutions', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Environment',
    text: 'Environmental problems such as climate change and pollution affect everyone around the world. Although efforts to tackle these problems are made on a global-scale, few solutions can be found. Why are so few solutions taken? How can these problems be solved?',
    questions: [q(1, 'cause', 'Why are so few solutions taken?'), q(2, 'solution', 'How can these problems be solved?')],
    reqs: ['Câu ①: giải thích vì sao nỗ lực toàn cầu ít mang lại giải pháp, không giải thích vì sao ô nhiễm xảy ra.', SOLUTION_REQ],
    driver: 'Few global solutions to environmental problems', stakeholders: ['Chính phủ các nước', 'Tổ chức quốc tế', 'Doanh nghiệp', 'Người dân'] },
  { id: 'weight-and-fitness', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Health',
    text: 'In some countries, the average weight of people is increasing and their levels of health and fitness are decreasing. What do you think are the causes of these problems and what measures can be taken to solve them?',
    questions: [q(1, 'cause', 'What do you think are the causes of these problems'), q(2, 'solution', 'what measures can be taken to solve them?')],
    reqs: ['Câu ①: giải thích vì sao cân nặng tăng và thể lực giảm.', SOLUTION_REQ],
    driver: 'Rising average weight and falling fitness', stakeholders: ['Người dân', 'Gia đình', 'Hệ thống y tế', 'Ngành thực phẩm'] },
  { id: 'throwaway-culture', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Environment',
    text: 'In many parts of the world, people now often throw things away when they are broken and buy new ones, whereas in the past broken things were repaired and used again. Why do you think this is the case? What problems may it lead to?',
    questions: [q(1, 'cause', 'Why do you think this is the case?'), q(2, 'problem', 'What problems may it lead to?')],
    reqs: ['Câu ①: giải thích vì sao người ta vứt đi thay vì sửa.', 'Câu ②: nêu vấn đề do thói quen này gây ra.'],
    driver: 'Throwing broken things away instead of repairing them', stakeholders: ['Người tiêu dùng', 'Nhà sản xuất', 'Thợ sửa chữa', 'Môi trường'] },
  { id: 'growing-cities-young-people', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Society and Culture',
    text: 'As major cities in the world are growing today, so do their problems. What are the problems for young people living in the cities as the result of continued growth? What are the solutions to these problems?',
    questions: [q(1, 'problem', 'What are the problems for young people living in the cities as the result of continued growth?'), q(2, 'solution', 'What are the solutions to these problems?')],
    reqs: ['Câu ①: nêu vấn đề của người trẻ do thành phố lớn lên, không phải vấn đề chung của đô thị.', 'Câu ②: mỗi giải pháp phải xử lý một vấn đề ở câu ①.'],
    driver: 'Continued growth of major cities', stakeholders: ['Người trẻ', 'Chính quyền thành phố', 'Chủ nhà, thị trường nhà ở', 'Doanh nghiệp'] },
  { id: 'money-management-skills', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Education',
    text: 'In many countries, students leave high school without understanding how to manage their money. Why is this? What solutions can be suggested to help students manage their finances effectively?',
    questions: [q(1, 'cause', 'Why is this?'), q(2, 'solution', 'What solutions can be suggested to help students manage their finances effectively?')],
    reqs: ['Câu ①: giải thích vì sao học sinh ra trường chưa biết quản lý tiền.', SOLUTION_REQ],
    driver: 'Students leaving school without money-management skills', stakeholders: ['Học sinh', 'Phụ huynh', 'Nhà trường', 'Ngân hàng'] },
  { id: 'imported-food', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Society and Culture',
    text: 'In many countries today, people are buying more imported food rather than food produced locally. What are the problems caused by this trend? What can be done to solve these problems?',
    questions: [q(1, 'problem', 'What are the problems caused by this trend?'), q(2, 'solution', 'What can be done to solve these problems?')],
    reqs: ['Câu ①: nêu vấn đề do mua thực phẩm nhập khẩu gây ra.', 'Câu ②: mỗi giải pháp phải xử lý một vấn đề ở câu ①.'],
    driver: 'People buying more imported food than local food', stakeholders: ['Nông dân trong nước', 'Người tiêu dùng', 'Môi trường', 'Chính phủ'] },
  { id: 'household-rubbish', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Environment',
    text: 'In many countries, the amount of household rubbish is increasing. What do you think are the causes of this problem? What can be done to solve it?',
    questions: [q(1, 'cause', 'What do you think are the causes of this problem?'), q(2, 'solution', 'What can be done to solve it?')],
    reqs: ['Câu ①: giải thích vì sao rác sinh hoạt tăng.', SOLUTION_REQ],
    driver: 'Rising household rubbish', stakeholders: ['Hộ gia đình', 'Nhà sản xuất, bao bì', 'Chính quyền', 'Môi trường'] },
  { id: 'elderly-care-decline', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Society and Culture',
    text: 'In many countries, family members and friends are spending less time looking after elderly relatives. What are the reasons for this? What effects does this have on the elderly and society?',
    questions: [q(1, 'cause', 'What are the reasons for this?'), q(2, 'effect', 'What effects does this have on the elderly and society?')],
    reqs: ['Câu ①: giải thích vì sao gia đình, bạn bè ít chăm người già hơn.', 'Câu ②: nêu ảnh hưởng tới cả người già lẫn xã hội.'],
    driver: 'Families spending less time caring for elderly relatives', stakeholders: ['Người già', 'Con cháu', 'Nhà dưỡng lão', 'Chính phủ'] },
  { id: 'young-and-old-apart', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Society and Culture',
    text: 'In many countries, young people are spending less time with older people. What are the reasons for this? What can be done to solve this problem?',
    questions: [q(1, 'cause', 'What are the reasons for this?'), q(2, 'solution', 'What can be done to solve this problem?')],
    reqs: ['Câu ①: giải thích vì sao người trẻ ít dành thời gian với người lớn tuổi.', SOLUTION_REQ],
    driver: 'Young people spending less time with older people', stakeholders: ['Người trẻ', 'Người lớn tuổi', 'Gia đình', 'Cộng đồng'] },
  { id: 'food-waste', source: YP + ' Collect', category: 'Causes, Problems and Solutions', topic: 'Environment',
    text: 'Every day, millions of tons of food are wasted all over the world. Why do you think this is happening? And how can we solve this problem?',
    questions: [q(1, 'cause', 'Why do you think this is happening?'), q(2, 'solution', 'And how can we solve this problem?')],
    reqs: ['Câu ①: giải thích vì sao thực phẩm bị lãng phí.', SOLUTION_REQ],
    driver: 'Millions of tons of food wasted every day', stakeholders: ['Hộ gia đình', 'Siêu thị, nhà hàng', 'Nông dân', 'Chính phủ'] },

  // ---------------- Two-Part Question ----------------
  { id: 'living-alone', source: SAMPLE, category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'In many countries, a growing number of young adults now choose to live alone. Why is this happening? Is this a positive or negative development?',
    questions: [q(1, 'cause', 'Why is this happening?'), q(2, 'verdict', 'Is this a positive or negative development?', ['Tiêu cực', 'Tích cực'])],
    reqs: ['Câu ①: giải thích vì sao người trẻ chọn sống một mình, không chỉ mô tả hiện tượng.', 'Câu ②: nói rõ đây là tích cực hay tiêu cực, và trong điều kiện nào.'],
    driver: 'Young adults choosing to live alone', stakeholders: ['Người trẻ', 'Gia đình', 'Chủ nhà / thị trường nhà ở', 'Chính phủ'] },
  { id: 'tourism-limits', source: SAMPLE, category: 'Two-Part Question', topic: 'Travel and Transportation',
    text: 'Tourism is growing fast in many popular cities. What problems does this cause? Do you agree that the number of tourists should be limited?',
    questions: [q(1, 'problem', 'What problems does this cause?'), q(2, 'verdict', 'Do you agree that the number of tourists should be limited?', ['Phản đối', 'Đồng ý'])],
    reqs: ['Câu ①: nêu vấn đề do du lịch tăng nhanh gây ra.', 'Câu ②: nói rõ có nên giới hạn khách hay không, và trong điều kiện nào.'],
    driver: 'Fast-growing tourism in popular cities', stakeholders: ['Cư dân', 'Doanh nghiệp du lịch', 'Du khách', 'Chính quyền'] },
  { id: 'rural-to-city', source: SAMPLE, category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'More and more young people are leaving rural areas to live in cities. What are the causes of this? What effects does it have?',
    questions: [q(1, 'cause', 'What are the causes of this?'), q(2, 'effect', 'What effects does it have?')],
    reqs: ['Câu ①: giải thích vì sao người trẻ rời nông thôn.', 'Câu ②: nêu ảnh hưởng tới nông thôn, thành phố hoặc chính người trẻ.'],
    driver: 'Young people moving from rural areas to cities', stakeholders: ['Người trẻ', 'Gia đình ở quê', 'Làng quê', 'Thành phố'] },
  { id: 'competitiveness', source: YP + ' · T04/2026', category: 'Two-Part Question', topic: 'Work and Careers',
    text: 'In many societies, competitiveness is regarded as an important personal quality. How does this affect individuals? Do you think this is a beneficial or harmful trend?',
    questions: [q(1, 'effect', 'How does this affect individuals?'), q(2, 'verdict', 'Do you think this is a beneficial or harmful trend?', ['Có hại', 'Có lợi'])],
    reqs: ['Câu ①: nêu ảnh hưởng tới từng cá nhân, cả tốt lẫn xấu.', 'Câu ②: nói rõ xu hướng này có lợi hay có hại, và với ai.'],
    driver: 'Treating competitiveness as an important personal quality', stakeholders: ['Cá nhân', 'Gia đình', 'Nơi làm việc', 'Trường học'] },
  { id: 'online-shopping-effects', source: YP + ' · 22/02/2020', category: 'Two-Part Question', topic: 'Environment',
    text: 'Online shopping is becoming more popular. How could this trend affect our environment and the kinds of work required?',
    questions: [q(1, 'effect', 'How could this trend affect our environment and the kinds of work required?')],
    reqs: ['Đề có một câu hỏi nhưng hai phần: ảnh hưởng tới môi trường và tới loại công việc cần có. Bàn cả hai.', 'Nêu ảnh hưởng của chính việc mua sắm online, không bàn chung về công nghệ.'],
    driver: 'Online shopping becoming more popular', stakeholders: ['Người tiêu dùng', 'Nhân viên giao hàng, kho bãi', 'Cửa hàng truyền thống', 'Môi trường'] },
  // Flagged: the first question asks "how important"; mapped to Ảnh hưởng (what ambition does for success).
  { id: 'ambition', source: YP + ' Collect', category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'Ambition is a positive quality for people to have in society today. How important is it for people who want to succeed in life? Is it a positive or negative characteristic?',
    questions: [q(1, 'effect', 'How important is it for people who want to succeed in life?'), q(2, 'verdict', 'Is it a positive or negative characteristic?', ['Tiêu cực', 'Tích cực'])],
    reqs: ['Câu ①: giải thích tham vọng giúp (hoặc không giúp) người muốn thành công như thế nào.', 'Câu ②: nói rõ đây là tính cách tích cực hay tiêu cực, và trong điều kiện nào.'],
    driver: 'Being ambitious', stakeholders: ['Cá nhân', 'Gia đình', 'Đồng nghiệp', 'Xã hội'] },
  { id: 'declining-science-students', source: YP + ' Collect', category: 'Two-Part Question', topic: 'Education',
    text: 'Fewer students are studying science subjects at university. What are the reasons for this? What are the effects on society?',
    questions: [q(1, 'cause', 'What are the reasons for this?'), q(2, 'effect', 'What are the effects on society?')],
    reqs: ['Câu ①: giải thích vì sao ít sinh viên chọn ngành khoa học.', 'Câu ②: nêu ảnh hưởng tới xã hội, không chỉ tới sinh viên.'],
    driver: 'Fewer students studying science at university', stakeholders: ['Sinh viên', 'Trường đại học', 'Doanh nghiệp', 'Xã hội'] },
  { id: 'young-population-effects', source: YP + ' Collect', category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'In some countries, the numbers of children aged 15 and younger are increasing dramatically. What are the current and future effects of an ever-increasing population?',
    questions: [q(1, 'effect', 'What are the current and future effects of an ever-increasing population?')],
    reqs: ['Đề có một câu hỏi nhưng hai mốc: ảnh hưởng hiện tại và tương lai. Bàn cả hai.', 'Nêu ảnh hưởng của dân số trẻ tăng nhanh, không bàn chung về dân số.'],
    driver: 'Rapid growth in the number of children aged 15 and under', stakeholders: ['Trẻ em', 'Gia đình', 'Trường học, y tế', 'Thị trường lao động tương lai'] },
  // Flagged: unusual wording, probably not a real exam prompt.
  { id: 'road-safety-legal-system', source: YP + ' Collect', category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'To what extent do you agree or disagree that stricter punishments are the only way to improve road safety? And, how might traffic laws and their enforcement influence the operation of the national legal system as a whole?',
    questions: [q(1, 'verdict', 'To what extent do you agree or disagree that stricter punishments are the only way to improve road safety?', ['Phản đối', 'Đồng ý']), q(2, 'effect', 'And, how might traffic laws and their enforcement influence the operation of the national legal system as a whole?')],
    reqs: ['Câu ①: nói rõ phạt nặng có phải cách duy nhất không.', 'Câu ②: nêu luật giao thông và việc thực thi ảnh hưởng tới cả hệ thống pháp luật thế nào.'],
    driver: 'Much stricter punishments for driving offences', driver2: 'Redesigning roads and adding speed cameras', claim: 'only', stakeholders: ['Người lái xe', 'Cảnh sát', 'Toà án', 'Chính phủ'] },
  { id: 'bicycle-investment', source: YP + ' Collect', category: 'Two-Part Question', topic: 'Society and Culture',
    text: 'Some countries spend a lot of money to make bicycle usage easier. Why is this? Is this the best solution to traffic congestion?',
    questions: [q(1, 'cause', 'Why is this?'), q(2, 'verdict', 'Is this the best solution to traffic congestion?', ['Không phải tốt nhất', 'Là tốt nhất'])],
    reqs: ['Câu ①: giải thích vì sao các nước đầu tư cho xe đạp.', 'Câu ②: nói rõ đây có phải giải pháp tốt nhất cho tắc đường không, so với các cách khác.'],
    driver: 'Countries spending heavily to make cycling easier', driver2: 'Countries investing in public transport such as buses and trains', claim: 'best', stakeholders: ['Người đi xe đạp', 'Người đi ô tô, xe máy', 'Chính quyền thành phố', 'Người đóng thuế'] },
  // ---------------- From the book (The Art of Nuance, Phase 2 examples) ----------------
  { id: 'advertising-economy-society', source: BOOK, category: 'Discussion', topic: 'Society and Culture', text: 'Some people say advertising has positive economic effects. Others think it has negative social effects because it will make people dissatisfied with who they are and what they have. Discuss both views and give your own opinion.', questions: dv('Discuss both views and give your own opinion.', 'Hại cho xã hội', 'Lợi cho kinh tế'), reqs: ['Bàn cả lợi ích kinh tế lẫn tác hại xã hội của quảng cáo.', 'Nói rõ bên nào nặng hơn, với ai và với loại quảng cáo nào.'], driver: 'Widespread advertising', stakeholders: ['Doanh nghiệp nhỏ', 'Thương hiệu lớn', 'Người tiêu dùng', 'Trẻ em, thanh thiếu niên', 'Chính phủ'] },
  { id: 'all-subjects-vs-strengths', source: BOOK, category: 'Discussion', topic: 'Education', text: 'Some people believe teenagers should focus on all subjects equally, whereas other people think that they should concentrate on only those subjects that they find interesting and they are best at. Discuss both these views and give your own opinion.', questions: dv('Discuss both these views and give your own opinion.', 'Tập trung môn giỏi', 'Học đều mọi môn'), reqs: DISCUSS_REQS, driver: 'Teenagers studying all subjects equally', driver2: 'Teenagers concentrating on the subjects they find interesting and are best at', stakeholders: ['Học sinh', 'Giáo viên', 'Phụ huynh', 'Nhà trường', 'Trường đại học'] },
  { id: 'compulsory-art-classes', source: BOOK, category: 'Agree or Disagree', topic: 'Education', text: 'Art classes such as painting or drawing are important for children\'s development, so they should be compulsory in high school. Do you agree or disagree?', questions: ag('Do you agree or disagree?'), reqs: ['Tách hai phần nối bằng chữ "so": học vẽ quan trọng cho trẻ em có kéo theo phải bắt buộc ở cấp ba không?', 'Xét chữ "compulsory": khác gì so với để học vẽ là môn tự chọn?'], driver: 'Making art classes compulsory in high school', stakeholders: ['Học sinh cấp ba', 'Trẻ em tiểu học', 'Nhà trường', 'Phụ huynh'] },
  { id: 'congestion-charges', source: BOOK, category: 'Positive or Negative Development', topic: 'Travel and Transportation', text: 'Some cities have introduced congestion charges during busy periods in order to reduce traffic. Is this a positive or negative development?', questions: pn('Is this a positive or negative development?'), reqs: ['Nói rõ đây là xu hướng tích cực hay tiêu cực.', 'Xét người không có cách đi lại nào khác ngoài ô tô, và thành phố có đủ giao thông công cộng hay không.'], driver: 'Charging drivers to enter busy areas at peak times', stakeholders: ['Người lái xe', 'Người đi xe buýt', 'Cư dân thành phố', 'Chính quyền thành phố'] },
  { id: 'educate-prisoners-work', source: BOOK, category: 'Agree or Disagree', topic: 'Government & Criminal Justice', text: 'The best way to reduce crime is to educate prisoners so that they can find work after they are released. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Nói rõ dạy nghề cho tù nhân có phải cách tốt nhất để giảm tội phạm không.', 'Chữ "the best way": cần so với các cách khác như tăng án tù, thêm cảnh sát.'], driver: 'Educating prisoners so they can find work after release', driver2: 'Increasing prison sentences and putting more police on the streets', claim: 'best', stakeholders: ['Tù nhân và người mãn hạn tù', 'Người phạm tội lần đầu', 'Chủ doanh nghiệp', 'Cảnh sát', 'Chính phủ'] },
  { id: 'growth-poverty-environment', source: BOOK, category: 'Discussion', topic: 'Economics', text: 'Some people believe that economic growth is the only way to reduce poverty and hunger, while others argue that economic growth can harm the environment. Discuss both views and give your own opinion.', questions: dv('Discuss both views and give your own opinion.', 'Hại môi trường', 'Cách duy nhất giảm nghèo'), reqs: ['Bàn cả hai quan điểm: tăng trưởng giảm nghèo, và tăng trưởng hại môi trường.', 'Xét chữ "only" và chữ "can": tăng trưởng có phải cách duy nhất không, và hại môi trường trong điều kiện nào.'], driver: 'Pursuing economic growth', driver2: 'Reducing poverty and hunger through other means, such as education, aid and fair trade', claim: 'only', stakeholders: ['Người nghèo', 'Chính phủ', 'Doanh nghiệp', 'Môi trường', 'Thế hệ sau'] },
  { id: 'maternity-leave', source: BOOK, category: 'Advantages and Disadvantages', topic: 'Work and Careers', text: 'In many countries, women are entitled to take maternity leave after giving birth. Do the advantages of maternity leave outweigh the disadvantages?', questions: ow('Do the advantages of maternity leave outweigh the disadvantages?'), reqs: ['So sánh ưu và nhược điểm của chế độ nghỉ thai sản, rồi nói bên nào nặng hơn.', 'Xét cả người mẹ, em bé lẫn nơi làm việc: vị trí dễ hay khó tìm người thay.'], driver: 'Women taking maternity leave after giving birth', stakeholders: ['Người mẹ', 'Em bé mới sinh', 'Người sử dụng lao động', 'Đồng nghiệp'] },
  { id: 'medical-vs-environment-research', source: BOOK, category: 'Agree or Disagree', topic: 'Science and Technology', text: 'Governments should spend more money on medical research and less on researching the environment. To what extent do you agree or disagree with this statement?', questions: ag('To what extent do you agree or disagree with this statement?'), reqs: ['Nói rõ có nên chuyển tiền từ nghiên cứu môi trường sang y học không, và với nước nào.', 'Cặp "more ... less": tiền thêm cho y học lấy từ môi trường, phải so cái được với cái mất.'], driver: 'Shifting government research funding from the environment to medicine', stakeholders: ['Người bệnh', 'Nhà khoa học', 'Chính phủ nước nghèo', 'Chính phủ nước giàu', 'Thế hệ sau'] },
  { id: 'older-workers-compete', source: BOOK, category: 'Causes, Problems and Solutions', topic: 'Work and Careers', text: 'Nowadays more and more people have to compete with young people for the same jobs. What problems does this cause? What are some possible solutions?', questions: [q(1, 'problem', 'What problems does this cause?'), q(2, 'solution', 'What are some possible solutions?')], reqs: ['Câu ①: nêu vấn đề cho cả người trẻ lẫn người lớn tuổi, không giải thích vì sao họ cạnh tranh.', 'Câu ②: mỗi giải pháp phải xử lý một vấn đề ở câu ①.'], driver: 'Older workers competing with young people for the same jobs', stakeholders: ['Sinh viên mới ra trường', 'Người lao động lớn tuổi', 'Nhà tuyển dụng', 'Trường đại học', 'Chính phủ'] },
  { id: 'peer-pressure', source: BOOK, category: 'Advantages and Disadvantages', topic: 'Society and Culture', text: 'Young people are often influenced by their peers. This is called peer group pressure. Do the advantages outweigh the disadvantages?', questions: ow('Do the advantages outweigh the disadvantages?'), reqs: ['Nói rõ lợi ích hay tác hại lớn hơn.', 'Xét lợi ích và tác hại phụ thuộc vào nhóm bạn đến mức nào.'], driver: 'Peer group pressure on young people', stakeholders: ['Thanh thiếu niên', 'Bạn bè', 'Phụ huynh', 'Nhà trường'] },
  { id: 'punish-parents', source: BOOK, category: 'Agree or Disagree', topic: 'Government & Criminal Justice', text: 'Some people believe that parents should be held responsible and punished when their children behave badly. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Nói rõ có nên phạt phụ huynh hay không, và trong điều kiện nào.', 'Phân biệt phụ huynh lơ là với phụ huynh đã cố gắng mà vẫn không quản được con.'], driver: 'Punishing parents when their children behave badly', stakeholders: ['Phụ huynh', 'Trẻ em, thanh thiếu niên', 'Nạn nhân và cộng đồng', 'Nhà trường', 'Chính quyền'] },
  { id: 'share-household-tasks', source: BOOK, category: 'Agree or Disagree', topic: 'Society and Culture', text: 'Nowadays, women as well as men work full-time. Therefore, women and men should share household tasks equally. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Nói rõ vợ chồng có nên chia sẻ việc nhà không, và chia thế nào.', 'Chữ "equally": chia đôi từng việc, hay công sức ngang nhau?'], driver: 'Couples who both work full-time sharing household tasks equally', stakeholders: ['Người vợ', 'Người chồng', 'Con cái', 'Nơi làm việc'] },
  { id: 'shopping-habits-age', source: BOOK, category: 'Agree or Disagree', topic: 'Society and Culture', text: 'People\'s shopping habits depend more on the age group that they belong to than other factors. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Nói rõ tuổi có quyết định nhiều hơn các yếu tố khác hay không.', 'Tự nêu các yếu tố khác (thu nhập, văn hoá, giá trị) để so với tuổi.'], driver: 'Age group as the main factor in shopping habits', stakeholders: ['Người trẻ', 'Người trung niên', 'Người lớn tuổi', 'Doanh nghiệp bán lẻ'] },
  { id: 'smoking-ban-public', source: BOOK, category: 'Agree or Disagree', topic: 'Health', text: 'Some people think that smoking should be banned in public places. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Nói rõ có nên cấm hút thuốc ở nơi công cộng hay không.', 'Cân sức khoẻ của người không hút với quyền tự do của người hút.'], driver: 'Banning smoking in public places', stakeholders: ['Người không hút thuốc', 'Người hút thuốc', 'Nhân viên nhà hàng, quán xá', 'Trẻ em', 'Chính phủ'] },
  { id: 'students-pay-full-fees', source: BOOK, category: 'Agree or Disagree', topic: 'Education', text: 'University students should pay the full cost of their studies because a university education benefits individuals rather than society as a whole. To what extent do you agree or disagree with this opinion?', questions: ag('To what extent do you agree or disagree with this opinion?'), reqs: ['Xét cả phần lý do ("rather than": cá nhân có được lợi hơn xã hội không?) lẫn phần kết luận.', 'Chữ "full cost": khác gì so với sinh viên chỉ đóng một phần?'], driver: 'Making university students pay the full cost of their studies', stakeholders: ['Sinh viên', 'Gia đình thu nhập thấp', 'Nhà nước', 'Trường đại học', 'Xã hội'] },
  { id: 'temporary-work', source: BOOK, category: 'Advantages and Disadvantages', topic: 'Work and Careers', text: 'Some people choose temporary jobs so that they have more time for other activities. Do the advantages of temporary work outweigh the disadvantages?', questions: ow('Do the advantages of temporary work outweigh the disadvantages?'), reqs: ['So sánh ưu và nhược điểm của việc làm tạm thời, rồi nói bên nào nặng hơn.', 'Đề nói "more time for other activities": xét thời gian rảnh thêm có thật sự được dùng vào việc gì đáng giá không.'], driver: 'Choosing temporary jobs to have more time for other activities', stakeholders: ['Người lao động tạm thời', 'Gia đình họ', 'Nhà tuyển dụng', 'Ngân hàng, bên cho vay'] },
  { id: 'traditional-vs-fast-food', source: BOOK, category: 'Agree or Disagree', topic: 'Society and Culture', text: 'In many countries, traditional foods are being replaced by international fast food. Some people think this is harmful for both families and societies. To what extent do you agree or disagree?', questions: ag('To what extent do you agree or disagree?'), reqs: ['Chữ "both": phải xét tác hại ở cả gia đình lẫn xã hội.', 'Chữ "replaced": bàn chuyện đồ ăn nhanh thay hẳn bữa truyền thống, không phải thỉnh thoảng ăn một bữa.'], driver: 'International fast food replacing traditional foods', stakeholders: ['Gia đình', 'Trẻ em', 'Hệ thống y tế', 'Xã hội và văn hoá địa phương', 'Chuỗi đồ ăn nhanh'] },
  { id: 'why-imported-food', source: BOOK, category: 'Causes, Problems and Solutions', topic: 'Economics', text: 'In many countries, more and more people choose to buy imported food rather than food produced locally. Why do people buy imported food? What could be done to encourage people to buy local food?', questions: [q(1, 'cause', 'Why do people buy imported food?'), q(2, 'solution', 'What could be done to encourage people to buy local food?')], reqs: ['Câu ①: giải thích vì sao người mua chọn đồ ăn nhập khẩu thay vì đồ trong nước.', SOLUTION_REQ], driver: 'Consumers choosing imported food over local food', stakeholders: ['Người mua', 'Nông dân trong nước', 'Siêu thị', 'Cơ quan an toàn thực phẩm'] },
  { id: 'working-hours-laws', source: BOOK, category: 'Two-Part Question', topic: 'Work and Careers', text: 'Some countries have introduced laws to limit the working hours that an employer can ask from an employee. Why are these laws introduced? Is this a positive or negative trend?', questions: [q(1, 'cause', 'Why are these laws introduced?'), q(2, 'verdict', 'Is this a positive or negative trend?', ['Tiêu cực', 'Tích cực'])], reqs: ['Câu ①: giải thích vì sao cần tới luật, không chỉ nói làm quá giờ có hại.', 'Câu ②: nói rõ đây là tích cực hay tiêu cực, và với ai.'], driver: 'Laws limiting working hours', stakeholders: ['Người lao động', 'Người lao động lương thấp', 'Người sử dụng lao động', 'Gia đình', 'Hệ thống y tế'] },
  { id: 'working-in-old-age', source: BOOK, category: 'Agree or Disagree', topic: 'Work and Careers', text: 'It is a good idea for people to continue working in their old age, if it is possible for them to do so. Do you agree or disagree?', questions: ag('Do you agree or disagree?'), reqs: ['Nói rõ đi làm tiếp khi về già có phải ý hay không, với những người còn làm được.', 'Cụm "if it is possible" đã loại người không đủ sức: đừng tách lại theo sức khoẻ.'], driver: 'Older people continuing to work when they are able to', stakeholders: ['Người lớn tuổi', 'Gia đình', 'Người lao động trẻ', 'Doanh nghiệp', 'Xã hội'] },
  { id: 'young-offenders-adults', source: BOOK, category: 'Agree or Disagree', topic: 'Government & Criminal Justice', text: 'Young people who commit crimes should be treated the same way as adults. To what extent do you agree or disagree with this statement?', questions: ag('To what extent do you agree or disagree with this statement?'), reqs: ['Xét chữ "the same way": có phải người trẻ phạm tội nào cũng nên bị xử như người lớn.', 'Phân biệt nhóm phạm tội lần đầu với nhóm phạm tội bạo lực nghiêm trọng.'], driver: 'Treating young offenders the same way as adults', stakeholders: ['Người trẻ phạm tội', 'Nạn nhân', 'Gia đình', 'Hệ thống tư pháp', 'Xã hội'] },
];

export const PROMPTS: Prompt[] = ENTRIES.map((e) => ({ ...e, task: 'task2' as const }));

const BY_ID = new Map(PROMPTS.map((p) => [p.id, p]));
export const findPrompt = (id: string): Prompt | null => BY_ID.get(id) || null;

/** Topic → illustration shown on library cards (no per-prompt photos). */
export const TOPIC_ILLUSTRATION: Record<Topic, string> = {
  'Education': 'il-study',
  'Environment': 'il-knowledge',
  'Work and Careers': 'il-achievement',
  'Government & Criminal Justice': 'il-review',
  'Science and Technology': 'il-thinking',
  'Health': 'il-progress',
  'Entertainment': 'il-announce',
  'Society and Culture': 'il-conversation',
  'Economics': 'il-grammar',
  'Other Topics': 'il-brainstorm',
  'Travel and Transportation': 'il-time',
};
