// Checks every Chép mẫu sample in src/content/samples/*.json and regenerates src/content/samples/index.ts.
// Run: node scripts/check-samples.mjs   (fails with a list of problems)
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const dir = path.join(root, 'src/content/samples');
const promptIds = new Set([...fs.readFileSync(path.join(root, 'src/content/prompts.ts'), 'utf8').matchAll(/\{ id: '([^']+)'/g)].map((m) => m[1]));
const TOOLS = new Set(['Đề hỏi gì', 'Lập trường', 'Mạch', 'Scope', 'With/Without', 'Dài hạn', 'Quy mô', 'Khả thi', 'Phản biện', 'Nối về']);

const problems = [];
const ids = [];
let words = [];
for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
  const id = file.replace(/\.json$/, '');
  const bad = (msg) => problems.push(`${file}: ${msg}`);
  let s;
  try { s = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')); } catch (e) { bad('invalid JSON: ' + e.message); continue; }
  if (s.promptId !== id) bad(`promptId "${s.promptId}" does not match the file name`);
  if (!promptIds.has(id)) bad('no prompt with this id in src/content/prompts.ts');
  if (!['book', 'hocnoihocviet'].includes(s.source)) bad('source must be "book" or "hocnoihocviet"');
  if (!Array.isArray(s.paragraphs) || s.paragraphs.length < 3 || s.paragraphs.length > 5) { bad('needs 3–5 paragraphs'); continue; }
  let n = 0;
  s.paragraphs.forEach((p, pi) => {
    if (!Array.isArray(p) || !p.length) bad(`paragraph ${pi + 1} is empty`);
    (p || []).forEach((seg, si) => {
      const at = `paragraph ${pi + 1}, sentence ${si + 1}`;
      if (!seg.en || !seg.vi || !seg.tool || !seg.mark) return bad(`${at}: needs en, vi, tool and mark`);
      seg.tool.split(' + ').forEach((t) => { if (!TOOLS.has(t)) bad(`${at}: unknown tool "${t}"`); });
      if (!seg.en.includes(seg.mark)) bad(`${at}: mark "${seg.mark}" is not in the sentence`);
      if (/\s{2,}/.test(seg.en) || seg.en !== seg.en.trim()) bad(`${at}: extra spaces in the sentence`);
      n += seg.en.split(/\s+/).length;
    });
  });
  if (s.paragraphs[0]?.[0]?.tool !== 'Đề hỏi gì') bad('the essay should open with a "Đề hỏi gì" sentence');
  // The book's own samples run a little longer; written samples aim for 250–320.
  if (n < 230 || n > (s.source === 'book' ? 380 : 340)) bad(`${n} words; aim for 250–320`);
  words.push(n);
  ids.push(id);
}

if (problems.length) {
  console.error(problems.join('\n'));
  console.error(`\n${problems.length} problem(s).`);
  process.exit(1);
}
fs.writeFileSync(path.join(dir, 'index.ts'), `// Generated by scripts/check-samples.mjs. Do not edit by hand.
/** Prompts that have a Chép mẫu sample essay. */
export const SAMPLE_IDS: ReadonlySet<string> = new Set(${JSON.stringify(ids)});
`);
console.log(`${ids.length} samples OK (${Math.min(...words)}–${Math.max(...words)} words).`);
